project_id: 'tidas'
preserve_hierarchy: true
files:
  - source: /content/docs/**/*.mdx
    ignore:
      - /content/docs/**/*.en.mdx
      - /content/docs/**/*.de.mdx
      - /content/docs/**/*.fr.mdx
    translation: /content/docs/**/%file_name%.%two_letters_code%.mdx
  - source: /content/docs/**/meta.json
    translation: /content/docs/**/meta.%two_letters_code%.json
