import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'category',
      label: 'Core Modules',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        {
          type: 'link',
          label: 'Guide for Life Cycle Database',
          description: 'Guideline for LCA and Carbon Footprint',
          href: 'https://www.carbonfootprint.network/docs/category/lca-database-guideline/',
        },
        {
          type: 'category',
          label: 'TIDAS Schema',
          link: {
            type: 'generated-index',
          },
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'core-modules/schema/tidas-schema-intro',
            },
            {
              type: 'link',
              label: 'TIDAS JSON Schema Download',
              description: 'Download the complete JSON schema file',
              href: 'https://github.com/tiangong-lca/tidas-tools/tree/main/src/tidas_tools/tidas/schemas',
            },
            {
              type: 'category',
              label: 'TIDAS JSON Schema',
              link: {
                type: 'generated-index',
              },
              collapsed: true,
              items: [
                {
                  type:'autogenerated',
                  dirName: 'core-modules/schema/schema-content',
                },
              ],
            },
            {
              type: 'doc',
              id: 'core-modules/schema/tidas-schema-validation',
            },
          ],
        },
        {
          type: 'link',
          label: 'Reference Package',
          description: 'Reference package for TIDAS',
          href: 'https://github.com/linancn/EF-reference-package-3.1-Correction',
        },
      ],
    },
    {
      type: 'category',
      label: 'TIDAS Tools',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tool',
        },
        {
          type: 'link',
          label: 'TIDAS Tools GitHub',
          description: 'TIDAS Tools GitHub Repository',
          href: 'https://github.com/tiangong-lca/tidas-tools/tree/main/src/tidas_tools',
        },
      ],  
    },
    {
      type: 'category',
      label: 'Integration',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'integration',
        },
      ],  
    },
    {
      type: 'category',
      label: 'TianGong LCA Platform',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        {
          type: 'link',
          label: 'TianGong LCA Platform',
          description: 'TianGong LCA Platform',
          href: 'https://lca.tiangong.earth/',
        },
        {
          type: 'link',
          label: 'TianGong LCA Tutorial',
          description: 'TianGong LCA Platform Documentation',
          href: 'https://docs.tiangong.earth/',
        },
      ],  
    },
    {
      type: 'category',
      label: 'Use Case',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'use_case',
        },
      ],  
    },
    {
      type: 'category',
      label: 'FAQ',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'faq',
        },
      ],  
    },
  ],
};

export default sidebars;
